// Stub catalog used when no Supabase env vars are configured. Lets
// `npm run dev` produce a browsable storefront on a fresh clone for
// design / a11y / responsive review.
//
// Never returned in production — gated on `isDemo` in lib/supabase.ts.

import type { BlogPost, Product, Category, Page } from '@/types';
import { deriveFreeFromClaims } from './free-from';

const TS = '2026-05-22T12:00:00.000Z';

// Demo catalogue — a representative slice of the live eBay inventory
// (`gorgeousbeaut_0`). Real product titles, UK GBP prices and eBay-hosted
// thumbnails so a fresh clone can render the storefront end-to-end without
// Supabase. Replaced wholesale once the inventory has been imported.
export const DEMO_PRODUCTS: Product[] = [
  {
    id: 'demo-1', brand: "Fair And White", name: "Fair And White Gold Ultimate Even Tone Revitalizing Body Lotion :1",
    slug: "demo-fair-and-white-gold-ultimate-even-tone-revitalizing-body-lotion-1-1",
    price: 22.49, category: "Body Lotions", subcategory: "Body Care",
    tag: 'Bestseller', stock: 63,
    image_url: "https://i.ebayimg.com/images/g/E64AAeSwBO9pRoXN/s-l500.webp",
    short_description: "Fair And White Gold Ultimate Even Tone Revitalizing Body Lotion :1",
    kind: 'simple', status: 'published', created_at: TS,
  },
  {
    id: 'demo-2', brand: "Fair And White", name: "Fair And White Gold Ultimate Even Tone Revitalizing Body Lotion 500ml",
    slug: "demo-fair-and-white-gold-ultimate-even-tone-revitalizing-body-lotion-500ml-2",
    price: 21.99, category: "Body Lotions", subcategory: "Body Care",
    stock: 38,
    image_url: "https://i.ebayimg.com/images/g/haQAAeSwR7JpIy7Z/s-l500.webp",
    short_description: "Fair And White Gold Ultimate Even Tone Revitalizing Body Lotion 500ml",
    kind: 'simple', status: 'published', created_at: TS,
  },
  {
    id: 'demo-3', brand: "KeraCare", name: "KeraCare UK Labled Natural Textures Leave-In Conditioner 474ml",
    slug: "demo-keracare-uk-labled-natural-textures-leave-in-conditioner-474ml-3",
    price: 17.79, category: "Curl & Styling Creams", subcategory: "Hair Care",
    stock: 82,
    image_url: "https://i.ebayimg.com/images/g/vOIAAeSwq4xpHx81/s-l500.webp",
    short_description: "KeraCare UK Labled Natural Textures Leave-In Conditioner 474ml",
    kind: 'simple', status: 'published', created_at: TS,
  },
  {
    id: 'demo-4', brand: "KeraCare", name: "KeraCare UK Labled Silken Seal 3 Hair Blow Drying Complex 120ml Smooth & Shine",
    slug: "demo-keracare-uk-labled-silken-seal-3-hair-blow-drying-complex-120ml-smooth-shine-4",
    price: 14.49, category: "Shampoo & Conditioner", subcategory: "Hair Care",
    stock: 58,
    image_url: "https://i.ebayimg.com/images/g/F9AAAeSw5eRpHwUd/s-l500.webp",
    short_description: "KeraCare UK Labled Silken Seal 3 Hair Blow Drying Complex 120ml Smooth & Shine",
    kind: 'simple', status: 'published', created_at: TS,
  },
  {
    id: 'demo-5', brand: "KeraCare", name: "KeraCare UK Labled Foam Wrap Set Mousse Extra Hold 3 Styling Mousse 240ml",
    slug: "demo-keracare-uk-labled-foam-wrap-set-mousse-extra-hold-3-styling-mousse-240ml-5",
    price: 14.49, category: "Mousse & Hairspray", subcategory: "Hair Care",
    stock: 75,
    image_url: "https://i.ebayimg.com/images/g/MbIAAeSwaXxpHwMT/s-l500.webp",
    short_description: "KeraCare UK Labled Foam Wrap Set Mousse Extra Hold 3 Styling Mousse 240ml",
    kind: 'simple', status: 'published', created_at: TS,
  },
  {
    id: 'demo-6', brand: "KeraCare", name: "KeraCare UK Labled Styling Spritz 3 Extra Hold Hair Spray 240ml",
    slug: "demo-keracare-uk-labled-styling-spritz-3-extra-hold-hair-spray-240ml-6",
    price: 13.49, category: "Mousse & Hairspray", subcategory: "Hair Care",
    stock: 54,
    image_url: "https://i.ebayimg.com/images/g/KYYAAeSwOcBpHwNc/s-l500.webp",
    short_description: "KeraCare UK Labled Styling Spritz 3 Extra Hold Hair Spray 240ml",
    kind: 'simple', status: 'published', created_at: TS,
  },
  {
    id: 'demo-7', brand: "ORS", name: "ORS Olive Oil Hold & Shine Wrap Set Mousse 7oz 207ml 2 Pack UK Free Post",
    slug: "demo-ors-olive-oil-hold-shine-wrap-set-mousse-7oz-207ml-2-pack-uk-free-post-7",
    price: 12.69, category: "Mousse & Hairspray", subcategory: "Hair Care",
    stock: 43,
    image_url: "https://i.ebayimg.com/images/g/nZAAAeSweTlpR-uB/s-l500.webp",
    short_description: "ORS Olive Oil Hold & Shine Wrap Set Mousse 7oz 207ml 2 Pack UK Free Post",
    kind: 'simple', status: 'published', created_at: TS,
  },
  {
    id: 'demo-8', brand: "Gabri", name: "Gabri Professional - Beard Oil Argan Oil 75ml",
    slug: "demo-gabri-professional-beard-oil-argan-oil-75ml-8",
    price: 11.99, category: "Beard Care", subcategory: "Grooming",
    stock: 87,
    image_url: "https://i.ebayimg.com/images/g/eHsAAeSwFDppe5UX/s-l500.webp",
    short_description: "Gabri Professional - Beard Oil Argan Oil 75ml",
    kind: 'simple', status: 'published', created_at: TS,
  },
  {
    id: 'demo-9', brand: "As I Am", name: "As I Am Dry & Itchy Scalp Leave-In Conditioner 8oz",
    slug: "demo-as-i-am-dry-itchy-scalp-leave-in-conditioner-8oz-9",
    price: 11.79, category: "Curl & Styling Creams", subcategory: "Hair Care",
    tag: 'Bestseller', stock: 90,
    image_url: "https://i.ebayimg.com/images/g/T4wAAeSwPYppSSyo/s-l500.webp",
    short_description: "As I Am Dry & Itchy Scalp Leave-In Conditioner 8oz",
    kind: 'simple', status: 'published', created_at: TS,
  },
  {
    id: 'demo-10', brand: "KeraCare", name: "KeraCare UK Labled Detangling Conditioning Mist 2 Leave-In Conditioner 240ml",
    slug: "demo-keracare-uk-labled-detangling-conditioning-mist-2-leave-in-conditioner-240ml-10",
    price: 11.49, category: "Curl & Styling Creams", subcategory: "Hair Care",
    stock: 76,
    image_url: "https://i.ebayimg.com/images/g/AYIAAeSwbllpHwLF/s-l500.webp",
    short_description: "KeraCare UK Labled Detangling Conditioning Mist 2 Leave-In Conditioner 240ml",
    kind: 'simple', status: 'published', created_at: TS,
  },
  {
    id: 'demo-11', brand: "KeraCare", name: "KeraCare UK Labled Edge Tamer 3 Extra Hold Smoothing Gel 115g",
    slug: "demo-keracare-uk-labled-edge-tamer-3-extra-hold-smoothing-gel-115g-11",
    price: 11.49, category: "Shampoo & Conditioner", subcategory: "Hair Care",
    stock: 40,
    image_url: "https://i.ebayimg.com/images/g/AHEAAeSwVNppHwQ5/s-l500.webp",
    short_description: "KeraCare UK Labled Edge Tamer 3 Extra Hold Smoothing Gel 115g",
    kind: 'simple', status: 'published', created_at: TS,
  },
  {
    id: 'demo-12', brand: "KeraCare", name: "KeraCare UK Labled Clear Protein Styling Gel 3 Extra Hold 455g",
    slug: "demo-keracare-uk-labled-clear-protein-styling-gel-3-extra-hold-455g-12",
    price: 11.49, category: "Edge Control & Gels", subcategory: "Hair Care",
    tag: 'New', stock: 52,
    image_url: "https://i.ebayimg.com/images/g/KgUAAeSw4VRpHwO6/s-l500.webp",
    short_description: "KeraCare UK Labled Clear Protein Styling Gel 3 Extra Hold 455g",
    kind: 'simple', status: 'published', created_at: TS,
  },
  {
    id: 'demo-13', brand: "Doo Gro", name: "DOO GRO Mega Thick Leave-In Conditioner 296ml – Strength & Growth",
    slug: "demo-doo-gro-mega-thick-leave-in-conditioner-296ml-strength-growth-13",
    price: 11.49, category: "Curl & Styling Creams", subcategory: "Hair Care",
    stock: 97,
    image_url: "https://i.ebayimg.com/images/g/m64AAeSwMRJpGH1y/s-l500.webp",
    short_description: "DOO GRO Mega Thick Leave-In Conditioner 296ml – Strength & Growth",
    kind: 'simple', status: 'published', created_at: TS,
  },
  {
    id: 'demo-14', brand: "Vaseline", name: "Vaseline Cocoa Radiant Body Oil 200ml | Deep Moisture & Soft Glow",
    slug: "demo-vaseline-cocoa-radiant-body-oil-200ml-deep-moisture-soft-glow-14",
    price: 11.49, category: "Body Oils", subcategory: "Body Care",
    stock: 49,
    image_url: "https://i.ebayimg.com/images/g/yzMAAeSwHHtpD09R/s-l500.webp",
    short_description: "Vaseline Cocoa Radiant Body Oil 200ml | Deep Moisture & Soft Glow",
    kind: 'simple', status: 'published', created_at: TS,
  },
  {
    id: 'demo-15', brand: "As I Am", name: "As I Am Classic Leave-In Conditioner 237ml – Moisturizing & Detangling Care",
    slug: "demo-as-i-am-classic-leave-in-conditioner-237ml-moisturizing-detangling-care-15",
    price: 10.99, category: "Curl & Styling Creams", subcategory: "Hair Care",
    stock: 28,
    image_url: "https://i.ebayimg.com/images/g/SWYAAeSwFVFpAfmi/s-l500.webp",
    short_description: "As I Am Classic Leave-In Conditioner 237ml – Moisturizing & Detangling Care",
    kind: 'simple', status: 'published', created_at: TS,
  },
  {
    id: 'demo-16', brand: "ApHogee", name: "ApHogee Balancing Moisturizer 473ml – Hydrate & Strengthen Hair",
    slug: "demo-aphogee-balancing-moisturizer-473ml-hydrate-strengthen-hair-16",
    price: 10.99, category: "Shampoo & Conditioner", subcategory: "Hair Care",
    stock: 73,
    image_url: "https://i.ebayimg.com/images/g/WpQAAeSwHbhpHzRp/s-l500.webp",
    short_description: "ApHogee Balancing Moisturizer 473ml – Hydrate & Strengthen Hair",
    kind: 'simple', status: 'published', created_at: TS,
  },
  {
    id: 'demo-17', brand: "Kuza", name: "Kuza Jamaican Black Castor Oil Set Original Extra Dark Coconut Argan Flaxseed",
    slug: "demo-kuza-jamaican-black-castor-oil-set-original-extra-dark-coconut-argan-flaxseed-17",
    price: 10.77, category: "Hair Oils & Serums", subcategory: "Hair Care",
    tag: 'Bestseller', stock: 55,
    image_url: "https://i.ebayimg.com/images/g/EeUAAeSwXBNp~Ize/s-l500.webp",
    short_description: "Kuza Jamaican Black Castor Oil Set Original Extra Dark Coconut Argan Flaxseed",
    kind: 'simple', status: 'published', created_at: TS,
  },
  {
    id: 'demo-18', brand: "Cantu", name: "Cantu Avocado Hydrating Hair Care Set Shampoo Conditioner Curl Cream Mousse",
    slug: "demo-cantu-avocado-hydrating-hair-care-set-shampoo-conditioner-curl-cream-mousse-18",
    price: 10.49, category: "Mousse & Hairspray", subcategory: "Hair Care",
    stock: 38,
    image_url: "https://i.ebayimg.com/images/g/r80AAeSw0k5p~LRO/s-l500.webp",
    short_description: "Cantu Avocado Hydrating Hair Care Set Shampoo Conditioner Curl Cream Mousse",
    kind: 'simple', status: 'published', created_at: TS,
  },
  {
    id: 'demo-19', brand: "As I Am", name: "As I Am Dry & Itchy Scalp Care Olive & Tea Tree Oil Treatment 120ml",
    slug: "demo-as-i-am-dry-itchy-scalp-care-olive-tea-tree-oil-treatment-120ml-19",
    price: 10.49, category: "Shampoo & Conditioner", subcategory: "Hair Care",
    stock: 66,
    image_url: "https://i.ebayimg.com/images/g/UBUAAeSwsU5pSSl8/s-l500.webp",
    short_description: "As I Am Dry & Itchy Scalp Care Olive & Tea Tree Oil Treatment 120ml",
    kind: 'simple', status: 'published', created_at: TS,
  },
  {
    id: 'demo-20', brand: "ApHogee", name: "ApHogee Hair Repair Set – Shampoos, Reconstructors, Protein & Gloss Spray",
    slug: "demo-aphogee-hair-repair-set-shampoos-reconstructors-protein-gloss-spray-20",
    price: 10.49, category: "Shampoo & Conditioner", subcategory: "Hair Care",
    stock: 52,
    image_url: "https://i.ebayimg.com/images/g/op0AAeSwCyppH0Sg/s-l500.webp",
    short_description: "ApHogee Hair Repair Set – Shampoos, Reconstructors, Protein & Gloss Spray",
    kind: 'simple', status: 'published', created_at: TS,
  },
  {
    id: 'demo-21', brand: "Doo Gro", name: "DOO GRO Mega Thick Formula Hair Oil 135ml – Strength & Growth Aid",
    slug: "demo-doo-gro-mega-thick-formula-hair-oil-135ml-strength-growth-aid-21",
    price: 10.49, category: "Hair Oils & Serums", subcategory: "Hair Care",
    stock: 52,
    image_url: "https://i.ebayimg.com/images/g/evkAAeSwAftpGIXT/s-l500.webp",
    short_description: "DOO GRO Mega Thick Formula Hair Oil 135ml – Strength & Growth Aid",
    kind: 'simple', status: 'published', created_at: TS,
  },
  {
    id: 'demo-22', brand: "As I Am", name: "As I Am Rosemary Shampoo 237ml – Strength & Scalp Revitalizing Cleanser",
    slug: "demo-as-i-am-rosemary-shampoo-237ml-strength-scalp-revitalizing-cleanser-22",
    price: 9.99, category: "Shampoo & Conditioner", subcategory: "Hair Care",
    stock: 70,
    image_url: "https://i.ebayimg.com/images/g/M5oAAeSwX3xpBLz~/s-l500.webp",
    short_description: "As I Am Rosemary Shampoo 237ml – Strength & Scalp Revitalizing Cleanser",
    kind: 'simple', status: 'published', created_at: TS,
  },
  {
    id: 'demo-23', brand: "Doo Gro", name: "DOO GRO Hair Vitalizer Anti-Itch Formula 113g – Soothes & Nourishes Scalp",
    slug: "demo-doo-gro-hair-vitalizer-anti-itch-formula-113g-soothes-nourishes-scalp-23",
    price: 9.99, category: "Shampoo & Conditioner", subcategory: "Hair Care",
    tag: 'New', stock: 93,
    image_url: "https://i.ebayimg.com/images/g/~0AAAeSwOjdpGI~5/s-l500.webp",
    short_description: "DOO GRO Hair Vitalizer Anti-Itch Formula 113g – Soothes & Nourishes Scalp",
    kind: 'simple', status: 'published', created_at: TS,
  },
  {
    id: 'demo-24', brand: "Vaseline", name: "Vaseline Brightening Lotion 600ml ? Even Tone & Deep Moisturizing Care",
    slug: "demo-vaseline-brightening-lotion-600ml-even-tone-deep-moisturizing-care-24",
    price: 9.99, category: "Petroleum Jelly", subcategory: "Body Care",
    stock: 69,
    image_url: "https://i.ebayimg.com/images/g/uEUAAeSwLHJpAeiV/s-l500.webp",
    short_description: "Vaseline Brightening Lotion 600ml ? Even Tone & Deep Moisturizing Care",
    kind: 'simple', status: 'published', created_at: TS,
  },
  {
    id: 'demo-25', brand: "Jergens", name: "Jergens Body Lotion Collection – Moisture, Shea, Coconut & Aloe",
    slug: "demo-jergens-body-lotion-collection-moisture-shea-coconut-aloe-295-946ml-25",
    variant: "295–946ml", price: 9.99, category: "Body Lotions", subcategory: "Body Care",
    tag: 'Bestseller', stock: 88,
    image_url: "https://i.ebayimg.com/images/g/bbkAAeSwUlNpA5J6/s-l500.webp",
    short_description: "Jergens Body Lotion Collection – Moisture, Shea, Coconut & Aloe (295–946ml)",
    kind: 'simple', status: 'published', created_at: TS,
  },
  {
    id: 'demo-26', brand: "Shine 'n Jam", name: "Shine 'n Jam Conditioning Gel Supreme Hold",
    slug: "demo-shine-n-jam-conditioning-gel-supreme-hold-4oz-8oz-26",
    variant: "4oz & 8oz", price: 9.49, category: "Edge Control & Gels", subcategory: "Hair Care",
    stock: 74,
    image_url: "https://i.ebayimg.com/images/g/IQEAAeSwcM9p-hfS/s-l500.webp",
    short_description: "Shine 'n Jam Conditioning Gel Supreme Hold (4oz & 8oz)",
    kind: 'simple', status: 'published', created_at: TS,
  },
  {
    id: 'demo-27', brand: "As I Am", name: "As I Am Rosemary Styling Mousse with Biotin",
    slug: "demo-as-i-am-rosemary-styling-mousse-with-biotin-237-ml-27",
    variant: "237 ml", price: 9.49, category: "Mousse & Hairspray", subcategory: "Hair Care",
    stock: 37,
    image_url: "https://i.ebayimg.com/images/g/mZYAAeSwCfhpSBHr/s-l500.webp",
    short_description: "As I Am Rosemary Styling Mousse with Biotin (237 ml)",
    kind: 'simple', status: 'published', created_at: TS,
  },
  {
    id: 'demo-28', brand: "Doo Gro", name: "DOO GRO Mega Thick Hair Vitalizer 113g – Strength & Growth Aid",
    slug: "demo-doo-gro-mega-thick-hair-vitalizer-113g-strength-growth-aid-28",
    price: 9.49, category: "Shampoo & Conditioner", subcategory: "Hair Care",
    stock: 70,
    image_url: "https://i.ebayimg.com/images/g/JdkAAeSwLvFpGH~S/s-l500.webp",
    short_description: "DOO GRO Mega Thick Hair Vitalizer 113g – Strength & Growth Aid",
    kind: 'simple', status: 'published', created_at: TS,
  },
  {
    id: 'demo-29', brand: "ApHogee", name: "ApHogee Pro Vitamin Leave-In Conditioner 237ml – Hydrate & Strengthen Hair",
    slug: "demo-aphogee-pro-vitamin-leave-in-conditioner-237ml-hydrate-strengthen-hair-29",
    price: 9.29, category: "Curl & Styling Creams", subcategory: "Hair Care",
    stock: 31,
    image_url: "https://i.ebayimg.com/images/g/YNYAAeSwR3JpHzTW/s-l500.webp",
    short_description: "ApHogee Pro Vitamin Leave-In Conditioner 237ml – Hydrate & Strengthen Hair",
    kind: 'simple', status: 'published', created_at: TS,
  },
  {
    id: 'demo-30', brand: "ORS", name: "ORS Olive Oil No-Lye Kit Extra Strength – Smooth & Shiny Finish",
    slug: "demo-ors-olive-oil-no-lye-kit-extra-strength-smooth-shiny-finish-30",
    price: 8.99, category: "Relaxers & Kits", subcategory: "Hair Care",
    stock: 35,
    image_url: "https://i.ebayimg.com/images/g/L44AAeSwA71pD0cw/s-l500.webp",
    short_description: "ORS Olive Oil No-Lye Kit Extra Strength – Smooth & Shiny Finish",
    kind: 'simple', status: 'published', created_at: TS,
  },
  {
    id: 'demo-31', brand: "ORS", name: "ORS Olive Oil No-Lye Kit Extra Strength – Smooth & Shiny Finish",
    slug: "demo-ors-olive-oil-no-lye-kit-extra-strength-smooth-shiny-finish-31",
    price: 8.99, category: "Relaxers & Kits", subcategory: "Hair Care",
    stock: 84,
    image_url: "https://i.ebayimg.com/images/g/q5gAAeSwjkBpCIwx/s-l500.webp",
    short_description: "ORS Olive Oil No-Lye Kit Extra Strength – Smooth & Shiny Finish",
    kind: 'simple', status: 'published', created_at: TS,
  },
  {
    id: 'demo-32', brand: "Palmer's", name: "Palmer's Cocoa Butter Formula Stretch Mark Cream with Vitamin E, 125 g",
    slug: "demo-palmers-cocoa-butter-formula-stretch-mark-cream-with-vitamin-e-125-g-32",
    price: 8.99, category: "Cocoa & Shea Butter", subcategory: "Body Care",
    stock: 98,
    image_url: "https://i.ebayimg.com/images/g/XXMAAeSw1L5pJxqN/s-l500.webp",
    short_description: "Palmer's Cocoa Butter Formula Stretch Mark Cream with Vitamin E, 125 g",
    kind: 'simple', status: 'published', created_at: TS,
  },
  {
    id: 'demo-33', brand: "Palmer's", name: "Palmer's Cocoa Butter Stretch Marks & Firming | Butter, Lotion & Massage Cream",
    slug: "demo-palmers-cocoa-butter-stretch-marks-firming-butter-lotion-massage-cream-33",
    price: 8.99, category: "Cocoa & Shea Butter", subcategory: "Body Care",
    tag: 'Bestseller', stock: 70,
    image_url: "https://i.ebayimg.com/images/g/WBkAAeSwbkZpCz9k/s-l500.webp",
    short_description: "Palmer's Cocoa Butter Stretch Marks & Firming | Butter, Lotion & Massage Cream",
    kind: 'simple', status: 'published', created_at: TS,
  },
  {
    id: 'demo-34', brand: "ApHogee", name: "ApHogee Two-Step Protein Treatment & Balancing Moisturizer",
    slug: "demo-aphogee-two-step-protein-treatment-balancing-moisturizer-34",
    price: 8.99, category: "Hair Treatments & Masks", subcategory: "Hair Care",
    tag: 'New', stock: 43,
    image_url: "https://i.ebayimg.com/images/g/sRYAAeSwg8FpA2o-/s-l500.webp",
    short_description: "ApHogee Two-Step Protein Treatment & Balancing Moisturizer",
    kind: 'simple', status: 'published', created_at: TS,
  },
  {
    id: 'demo-35', brand: "Africa", name: "African Pride Olive Oil Deep Conditioning Relaxer – Regular Strength",
    slug: "demo-african-pride-olive-oil-deep-conditioning-relaxer-regular-strength-35",
    price: 8.99, category: "Relaxers & Kits", subcategory: "Hair Care",
    stock: 66,
    image_url: "https://i.ebayimg.com/images/g/XVUAAeSw5YppAfKP/s-l500.webp",
    short_description: "African Pride Olive Oil Deep Conditioning Relaxer – Regular Strength",
    kind: 'simple', status: 'published', created_at: TS,
  },
  {
    id: 'demo-36', brand: "Got2b", name: "Got2b Glued Spiking Glue 150ml | Water Resistant Extreme Hold Styling Gel",
    slug: "demo-got2b-glued-spiking-glue-150ml-water-resistant-extreme-hold-styling-gel-36",
    price: 8.79, category: "Edge Control & Gels", subcategory: "Hair Care",
    stock: 78,
    image_url: "https://i.ebayimg.com/images/g/Ey8AAeSwNIdpEx~E/s-l500.webp",
    short_description: "Got2b Glued Spiking Glue 150ml | Water Resistant Extreme Hold Styling Gel",
    kind: 'simple', status: 'published', created_at: TS,
  },
  {
    id: 'demo-37', brand: "Kuza", name: "Kuza Jamaican Black Castor Oil Hair Care Set Shampoo Conditioner and all",
    slug: "demo-kuza-jamaican-black-castor-oil-hair-care-set-shampoo-conditioner-and-all-37",
    price: 8.49, category: "Hair Oils & Serums", subcategory: "Hair Care",
    stock: 78,
    image_url: "https://i.ebayimg.com/images/g/uPYAAeSwKRRp~H4t/s-l500.webp",
    short_description: "Kuza Jamaican Black Castor Oil Hair Care Set Shampoo Conditioner and all",
    kind: 'simple', status: 'published', created_at: TS,
  },
  {
    id: 'demo-38', brand: "Africa", name: "African Pride Olive Miracle Anti-Breakage Leave-In Conditioner 425g",
    slug: "demo-african-pride-olive-miracle-anti-breakage-leave-in-conditioner-425g-38",
    price: 8.49, category: "Curl & Styling Creams", subcategory: "Hair Care",
    stock: 46,
    image_url: "https://i.ebayimg.com/images/g/LVwAAeSwuWVpKcDz/s-l500.webp",
    short_description: "African Pride Olive Miracle Anti-Breakage Leave-In Conditioner 425g",
    kind: 'simple', status: 'published', created_at: TS,
  },
  {
    id: 'demo-39', brand: "Cantu", name: "Cantu Avocado Repair Leave-In Cream 340g | Moisturize & Strengthen Hair",
    slug: "demo-cantu-avocado-repair-leave-in-cream-340g-moisturize-strengthen-hair-39",
    price: 8.49, category: "Curl & Styling Creams", subcategory: "Hair Care",
    stock: 65,
    image_url: "https://i.ebayimg.com/images/g/bmYAAeSwZA9pEefW/s-l500.webp",
    short_description: "Cantu Avocado Repair Leave-In Cream 340g | Moisturize & Strengthen Hair",
    kind: 'simple', status: 'published', created_at: TS,
  },
  {
    id: 'demo-40', brand: "Palmer's", name: "Palmer's Hair Food Formula - Nourishing A, B & E + Protein 5.25oz/150g",
    slug: "demo-palmers-hair-food-formula-nourishing-a-b-e-protein-5-25oz-150g-40",
    price: 8.49, category: "Shampoo & Conditioner", subcategory: "Hair Care",
    stock: 78,
    image_url: "https://i.ebayimg.com/images/g/kyUAAeSwEZho5mxX/s-l500.webp",
    short_description: "Palmer's Hair Food Formula - Nourishing A, B & E + Protein 5.25oz/150g",
    kind: 'simple', status: 'published', created_at: TS,
  },
  {
    id: 'demo-41', brand: "Kuza", name: "Kuza Indian Hemp Hair & Scalp Treatment – Growth & Strength",
    slug: "demo-kuza-indian-hemp-hair-scalp-treatment-growth-strength-113-510g-41",
    variant: "113–510g", price: 7.99, category: "Shampoo & Conditioner", subcategory: "Hair Care",
    tag: 'Sale', stock: 79,
    image_url: "https://i.ebayimg.com/images/g/1-sAAeSwc3VpAhy7/s-l500.webp",
    short_description: "Kuza Indian Hemp Hair & Scalp Treatment – Growth & Strength (113–510g)",
    kind: 'simple', status: 'published', created_at: TS,
  },
  {
    id: 'demo-42', brand: "ORS", name: "ORS Hair Care & Styling Bundle – Shampoo, Leave-In, Heat Serum, Oils & Curl Mous",
    slug: "demo-ors-hair-care-styling-bundle-shampoo-leave-in-heat-serum-oils-curl-mous-42",
    price: 7.99, category: "Curl & Styling Creams", subcategory: "Hair Care",
    tag: 'Sale', stock: 53,
    image_url: "https://i.ebayimg.com/images/g/baQAAeSwBCxpRtc7/s-l500.webp",
    short_description: "ORS Hair Care & Styling Bundle – Shampoo, Leave-In, Heat Serum, Oils & Curl Mous",
    kind: 'simple', status: 'published', created_at: TS,
  },
  {
    id: 'demo-43', brand: "Cantu", name: "Cantu Deep Treatment Masque 340g Shea Butter for Natural Curls, Coils & Waves",
    slug: "demo-cantu-deep-treatment-masque-340g-shea-butter-for-natural-curls-coils-waves-43",
    price: 7.99, category: "Cocoa & Shea Butter", subcategory: "Body Care",
    tag: 'Sale', stock: 88,
    image_url: "https://i.ebayimg.com/images/g/~cUAAeSwSj9pIIyh/s-l500.webp",
    short_description: "Cantu Deep Treatment Masque 340g Shea Butter for Natural Curls, Coils & Waves",
    kind: 'simple', status: 'published', created_at: TS,
  },
  {
    id: 'demo-44', brand: "Cantu", name: "Cantu Shea Butter Complete Conditioning Co‑Wash 283g | Gentle Cleanse",
    slug: "demo-cantu-shea-butter-complete-conditioning-co-wash-283g-gentle-cleanse-44",
    price: 7.99, category: "Cocoa & Shea Butter", subcategory: "Body Care",
    tag: 'Sale', stock: 47,
    image_url: "https://i.ebayimg.com/images/g/kL4AAeSwiG5pEfKG/s-l500.webp",
    short_description: "Cantu Shea Butter Complete Conditioning Co‑Wash 283g | Gentle Cleanse",
    kind: 'simple', status: 'published', created_at: TS,
  },
  {
    id: 'demo-45', brand: "Cantu", name: "Cantu for Kids Styling Custard 277g – Define, Hold & Moisturize Hair",
    slug: "demo-cantu-for-kids-styling-custard-277g-define-hold-moisturize-hair-45",
    price: 7.99, category: "Shampoo & Conditioner", subcategory: "Hair Care",
    tag: 'Sale', stock: 39,
    image_url: "https://i.ebayimg.com/images/g/vZYAAeSwEOxpG0FZ/s-l500.webp",
    short_description: "Cantu for Kids Styling Custard 277g – Define, Hold & Moisturize Hair",
    kind: 'simple', status: 'published', created_at: TS,
  },
  {
    id: 'demo-46', brand: "Cantu", name: "Cantu for Kids Leave-In Conditioner 283g – Moisturize, Detangle & Soft Hair",
    slug: "demo-cantu-for-kids-leave-in-conditioner-283g-moisturize-detangle-soft-hair-46",
    price: 7.99, category: "Curl & Styling Creams", subcategory: "Hair Care",
    tag: 'Sale', stock: 70,
    image_url: "https://i.ebayimg.com/images/g/ynkAAeSwR~VpG0Hx/s-l500.webp",
    short_description: "Cantu for Kids Leave-In Conditioner 283g – Moisturize, Detangle & Soft Hair",
    kind: 'simple', status: 'published', created_at: TS,
  },
  {
    id: 'demo-47', brand: "Got2b", name: "Got2b Ultra Glued Styling Gel for Edges 150ml | Maximum Hold | Choose Option",
    slug: "demo-got2b-ultra-glued-styling-gel-for-edges-150ml-maximum-hold-choose-option-47",
    price: 7.99, category: "Edge Control & Gels", subcategory: "Hair Care",
    tag: 'Sale', stock: 59,
    image_url: "https://i.ebayimg.com/images/g/2mkAAeSwMFNpEybe/s-l500.webp",
    short_description: "Got2b Ultra Glued Styling Gel for Edges 150ml | Maximum Hold | Choose Option",
    kind: 'simple', status: 'published', created_at: TS,
  },
  {
    id: 'demo-48', brand: "ORS", name: "ORS Lock & Twist Gel 368g – Natural Styling Gel for Locs & Braids",
    slug: "demo-ors-lock-twist-gel-368g-natural-styling-gel-for-locs-braids-48",
    price: 7.99, category: "Edge Control & Gels", subcategory: "Hair Care",
    tag: 'Sale', stock: 59,
    image_url: "https://i.ebayimg.com/images/g/KOkAAeSw8FhpBORr/s-l500.webp",
    short_description: "ORS Lock & Twist Gel 368g – Natural Styling Gel for Locs & Braids",
    kind: 'simple', status: 'published', created_at: TS,
  },
  {
    id: 'demo-49', brand: "ORS", name: "ORS & Bump Stopper Shaving Set – Anti-Bump Spray, Lotion & Beard Care",
    slug: "demo-ors-bump-stopper-shaving-set-anti-bump-spray-lotion-beard-care-49",
    price: 7.99, category: "Bump Treatments", subcategory: "Grooming",
    tag: 'Sale', stock: 53,
    image_url: "https://i.ebayimg.com/images/g/s4cAAeSwxp5pA4Pl/s-l500.webp",
    short_description: "ORS & Bump Stopper Shaving Set – Anti-Bump Spray, Lotion & Beard Care",
    kind: 'simple', status: 'published', created_at: TS,
  },
  {
    id: 'demo-50', brand: "Palmer's", name: "Palmer's Tahitiam Vanilla Body lotion 250ml, Luxurious Hydration .",
    slug: "demo-palmers-tahitiam-vanilla-body-lotion-250ml-luxurious-hydration-50",
    price: 7.99, category: "Body Lotions", subcategory: "Body Care",
    tag: 'Sale', stock: 76,
    image_url: "https://i.ebayimg.com/images/g/5fsAAeSw8IZpAkhj/s-l500.webp",
    short_description: "Palmer's Tahitiam Vanilla Body lotion 250ml, Luxurious Hydration .",
    kind: 'simple', status: 'published', created_at: TS,
  },
  {
    id: 'demo-51', brand: "Kuza", name: "Kuza Bees Wax Hair & Braid Conditioner 226g – Styling & Moisture",
    slug: "demo-kuza-bees-wax-hair-braid-conditioner-226g-styling-moisture-51",
    price: 7.89, category: "Shampoo & Conditioner", subcategory: "Hair Care",
    tag: 'Sale', stock: 83,
    image_url: "https://i.ebayimg.com/images/g/Z5cAAeSwBw5pHg5c/s-l500.webp",
    short_description: "Kuza Bees Wax Hair & Braid Conditioner 226g – Styling & Moisture",
    kind: 'simple', status: 'published', created_at: TS,
  },
  {
    id: 'demo-52', brand: "ORS", name: "ORS Olive Oil Moisturising Hair Lotion with Castor Oil 251ml Hair Growth",
    slug: "demo-ors-olive-oil-moisturising-hair-lotion-with-castor-oil-251ml-hair-growth-52",
    price: 7.69, category: "Hair Oils & Serums", subcategory: "Hair Care",
    tag: 'Sale', stock: 59,
    image_url: "https://i.ebayimg.com/images/g/1noAAeSw27JpR-Nq/s-l500.webp",
    short_description: "ORS Olive Oil Moisturising Hair Lotion with Castor Oil 251ml Hair Growth",
    kind: 'simple', status: 'published', created_at: TS,
  },
  {
    id: 'demo-53', brand: "Sulfur8", name: "Sulfur8 Hair & Scalp Care Set – Shampoo, Conditioner & Treatment",
    slug: "demo-sulfur8-hair-scalp-care-set-shampoo-conditioner-treatment-100-356ml-53",
    variant: "100–356ml", price: 7.69, category: "Shampoo & Conditioner", subcategory: "Hair Care",
    tag: 'Sale', stock: 52,
    image_url: "https://i.ebayimg.com/images/g/tfsAAeSw3ttpAg5E/s-l500.webp",
    short_description: "Sulfur8 Hair & Scalp Care Set – Shampoo, Conditioner & Treatment (100–356ml)",
    kind: 'simple', status: 'published', created_at: TS,
  },
  {
    id: 'demo-54', brand: "As I Am", name: "As I Am Rosemary Collection – Choose Shampoo, Conditioner, Mousse or Water",
    slug: "demo-as-i-am-rosemary-collection-choose-shampoo-conditioner-mousse-or-water-54",
    price: 7.58, category: "Mousse & Hairspray", subcategory: "Hair Care",
    tag: 'Sale', stock: 32,
    image_url: "https://i.ebayimg.com/images/g/bUMAAeSw3NlpSoNM/s-l500.webp",
    short_description: "As I Am Rosemary Collection – Choose Shampoo, Conditioner, Mousse or Water",
    kind: 'simple', status: 'published', created_at: TS,
  },
  {
    id: 'demo-55', brand: "Got2b", name: "got2b Dry Shampoo Extra Texture Instant Fresh Up 200ml",
    slug: "demo-got2b-dry-shampoo-extra-texture-instant-fresh-up-200ml-55",
    price: 7.49, category: "Mousse & Hairspray", subcategory: "Hair Care",
    tag: 'Sale', stock: 51,
    image_url: "https://i.ebayimg.com/images/g/-LwAAeSwZqJp~Guf/s-l500.webp",
    short_description: "got2b Dry Shampoo Extra Texture Instant Fresh Up 200ml",
    kind: 'simple', status: 'published', created_at: TS,
  },
  {
    id: 'demo-56', brand: "Africa", name: "Africa’s Best Cholesterol Leave-In Conditioner 426g | Moisturize & Strengthen Ha",
    slug: "demo-africa-s-best-cholesterol-leave-in-conditioner-426g-moisturize-strengthen-ha-56",
    price: 7.49, category: "Curl & Styling Creams", subcategory: "Hair Care",
    tag: 'Sale', stock: 20,
    image_url: "https://i.ebayimg.com/images/g/PfgAAeSwl2dpCfkh/s-l500.webp",
    short_description: "Africa’s Best Cholesterol Leave-In Conditioner 426g | Moisturize & Strengthen Ha",
    kind: 'simple', status: 'published', created_at: TS,
  },
  {
    id: 'demo-57', brand: "Cantu", name: "Cantu Shea Butter Sulfate-Free Cleansing Cream Shampoo 400ml",
    slug: "demo-cantu-shea-butter-sulfate-free-cleansing-cream-shampoo-400ml-57",
    price: 7.49, category: "Shampoo & Conditioner", subcategory: "Hair Care",
    tag: 'Sale', stock: 98,
    image_url: "https://i.ebayimg.com/images/g/dhwAAeSwNIdpELau/s-l500.webp",
    short_description: "Cantu Shea Butter Sulfate-Free Cleansing Cream Shampoo 400ml",
    kind: 'simple', status: 'published', created_at: TS,
  },
  {
    id: 'demo-58', brand: "Just for Me", name: "Just For Me Curl Peace Hair Care Set – Shampoo, Conditioner & Styling",
    slug: "demo-just-for-me-curl-peace-hair-care-set-shampoo-conditioner-styling-58",
    price: 7.49, category: "Shampoo & Conditioner", subcategory: "Hair Care",
    tag: 'Sale', stock: 42,
    image_url: "https://i.ebayimg.com/images/g/8SAAAeSwCB5pB5Fg/s-l500.webp",
    short_description: "Just For Me Curl Peace Hair Care Set – Shampoo, Conditioner & Styling",
    kind: 'simple', status: 'published', created_at: TS,
  },
  {
    id: 'demo-59', brand: "Just for Me", name: "Just For Me Natural Hair Milk Set – Shampoo, Conditioner & Styling Care",
    slug: "demo-just-for-me-natural-hair-milk-set-shampoo-conditioner-styling-care-59",
    price: 7.49, category: "Shampoo & Conditioner", subcategory: "Hair Care",
    tag: 'Sale', stock: 84,
    image_url: "https://i.ebayimg.com/images/g/74gAAeSwbMFpB45X/s-l500.webp",
    short_description: "Just For Me Natural Hair Milk Set – Shampoo, Conditioner & Styling Care",
    kind: 'simple', status: 'published', created_at: TS,
  },
  {
    id: 'demo-60', brand: "ORS", name: "ORS Olive Oil Girls Hair & Scalp Lotion 251ml – Moisture & Daily Nourishment",
    slug: "demo-ors-olive-oil-girls-hair-scalp-lotion-251ml-moisture-daily-nourishment-60",
    price: 7.19, category: "Shampoo & Conditioner", subcategory: "Hair Care",
    tag: 'Sale', stock: 58,
    image_url: "https://i.ebayimg.com/images/g/r5UAAeSw2KFpGyUi/s-l500.webp",
    short_description: "ORS Olive Oil Girls Hair & Scalp Lotion 251ml – Moisture & Daily Nourishment",
    kind: 'simple', status: 'published', created_at: TS,
  },
];

// Apply the free-from heuristic once at module load so the storefront
// filter rail has data to filter against in demo mode. In production
// the column is populated server-side (admin form / one-off backfill);
// this loop is a no-op on real Supabase rows because we never reach
// this file when env vars are set.
for (const p of DEMO_PRODUCTS) {
  const claims = deriveFreeFromClaims({
    name: p.name,
    short_description: p.short_description,
    description: p.description,
    ingredients: p.ingredients,
    brand: p.brand,
    category: p.category,
  });
  if (claims.length > 0) p.free_from = claims;
}

export const DEMO_CATEGORIES: Category[] = [
  { id: 'demo-cat-1', parent_id: null, slug: 'hair-care', name: 'Hair Care', description: null, image_url: undefined, sort_order: 0 },
  { id: 'demo-cat-2', parent_id: null, slug: 'body-care', name: 'Body Care', description: null, image_url: undefined, sort_order: 1 },
  { id: 'demo-cat-3', parent_id: null, slug: 'styling',   name: 'Styling & Tools', description: null, image_url: undefined, sort_order: 2 },
  { id: 'demo-cat-4', parent_id: null, slug: 'grooming',  name: 'Grooming', description: null, image_url: undefined, sort_order: 3 },
];

export const DEMO_BLOG_POSTS: BlogPost[] = [
  {
    id: 'demo-blog-1', slug: 'demo-wash-day-routine', title: 'A no-stress wash day routine for natural curls',
    excerpt: 'Cantu, ApHogee and a slow Sunday afternoon — the five-step routine that actually works.',
    category: 'Hair Care',
    date: '2026-05-10', read_time: '5 min read', featured: true,
    image_url: 'https://i.ebayimg.com/images/g/sRYAAeSwg8FpA2o-/s-l500.webp',
    body: '<p>Wash day used to mean a whole afternoon lost to a sticky bathroom floor and three half-empty bottles. Here is the five-step rhythm we land on for most type 3 and type 4 curls — slow enough to be kind, short enough to actually finish before dinner.</p>'
      + '<h2>1. Pre-poo with a heavy oil</h2>'
      + '<p>Apply castor or coconut oil from mid-length to ends, finger-detangle gently, and let it sit for 20–30 minutes under a shower cap. This is the difference between snapping curls in the shampoo lather and lifting them out intact.</p>'
      + '<h2>2. Cleanse — but only where it matters</h2>'
      + '<p>Use a sulphate-free cleanser on the scalp only and let the suds rinse down through the lengths. Two passes is plenty; a third strips the cuticle and undoes the pre-poo you just did.</p>'
      + '<h2>3. Protein, then moisture — never the other way around</h2>'
      + '<p>Once a month, work an ApHogee Two-Step or a similar reconstructor through soaked hair. Follow with a moisturising mask the same session so the cuticle resets soft instead of stiff. The order matters.</p>'
      + '<h2>4. Style on soaking-wet hair</h2>'
      + '<p>Cream, then gel, then plop in a cotton T-shirt. Working on wet hair locks the cream in before evaporation pulls moisture back out — this single change is the biggest reason curls clump on day one and stay clumped on day three.</p>'
      + '<h2>5. Dry low, sleep on satin</h2>'
      + '<p>Diffuse on low heat or air-dry; a bonnet or satin pillowcase keeps the curl pattern intact through the night. Skip this step and day-two hair is frizzy regardless of how good steps 1–4 were.</p>'
      + '<p>One routine, three or four products, one Sunday afternoon — and the curls look the same on Wednesday as they did on Monday.</p>',
    created_at: TS,
  },
  {
    id: 'demo-blog-2', slug: 'demo-jbco-explained', title: 'Jamaican Black Castor Oil, explained',
    excerpt: 'Original vs Extra Dark — which one your hair actually needs and how to use them.',
    category: 'Hair Care',
    date: '2026-05-04', read_time: '6 min read', featured: false,
    image_url: 'https://i.ebayimg.com/images/g/EeUAAeSwXBNp~Ize/s-l500.webp',
    body: '<p>If you have ever walked the hair-care aisle and squinted at two near-identical bottles of Jamaican Black Castor Oil — one labelled <em>Original</em>, the other <em>Extra Dark</em> — you are not alone. The bottles cost the same and look the same. The oil inside does not.</p>'
      + '<h2>What makes it &ldquo;black&rdquo; in the first place</h2>'
      + '<p>JBCO starts as castor beans roasted over wood-fire, ground to a paste, then boiled to separate the oil. The roast is what turns clear castor oil into the dark, ash-scented amber you find in the bottle — and it is also what people swear by for scalp circulation.</p>'
      + '<h2>Original — for moisture and shine</h2>'
      + '<p>The standard roast is the all-rounder. Sealed-in moisture, glossy ends, less daytime frizz. Warm a teaspoon between your palms and run it through damp lengths after styling; do not load it onto the scalp unless you are doing a full pre-poo.</p>'
      + '<h2>Extra Dark — for growth and edges</h2>'
      + '<p>The deeper roast concentrates the ricinoleic acid that gives JBCO its scalp-stimulating reputation. Apply directly to the edges, hairline and any thinning patches three nights a week. Give it eight weeks before you decide if it is working — castor oil is a slow, cumulative product, not an overnight fix.</p>'
      + '<h2>How to actually use it without weighing curls down</h2>'
      + '<p>JBCO is heavy. A pea-sized amount is plenty for the lengths, and a single drop at each temple is enough for the edges. Too much and you will spend the next two wash days clarifying it back out. Less is genuinely more here.</p>'
      + '<h2>One bottle, both bases covered</h2>'
      + '<p>If you can only buy one, start with Original — its moisture pay-off is universal. Add Extra Dark only when you have a specific edge or growth goal in mind. Either way, store the bottle out of direct sunlight; oxidised castor smells exactly as bad as it sounds.</p>',
    created_at: TS,
  },
  {
    id: 'demo-blog-3', slug: 'demo-cocoa-shea-difference', title: 'Cocoa vs shea butter — which one is right for you',
    excerpt: 'Both are body care heroes. Here\'s when to reach for each one (and when to layer both).',
    category: 'Body Care',
    date: '2026-04-28', read_time: '4 min read', featured: false,
    image_url: 'https://i.ebayimg.com/images/g/XXMAAeSw1L5pJxqN/s-l500.webp',
    body: '<p>Cocoa butter and shea butter both turn up in nearly every Black body-care brand on the shelf, often in the same product. They are not interchangeable, and picking the right one for the right job changes how your skin actually feels by the end of the week.</p>'
      + '<h2>Cocoa butter — for elasticity and that signature scent</h2>'
      + '<p>Cocoa butter is solid at room temperature and melts on contact with skin. It is rich in antioxidants and the kind of fatty acids that support elasticity, which is why it is the hero ingredient in nearly every stretch-mark cream you have ever heard of. It is also the one with the chocolate-y, warm scent that does not need a fragrance house to make it lovable.</p>'
      + '<h2>Shea butter — for dry, reactive skin</h2>'
      + '<p>Raw shea is softer at room temperature and absorbs faster than cocoa. It carries vitamin A and E, sits well on eczema-prone or irritated skin, and rarely triggers the breakouts that occlusive products sometimes do on the chest and back. The trade-off: a nuttier, more savoury scent that some people love and some people mask with body oil on top.</p>'
      + '<h2>When to reach for which</h2>'
      + '<p>Post-shower on dewy skin, when you want hydration to lock in and a light fragrance to last: cocoa. After a hot bath when your skin feels tight, or on a child with dry winter patches: shea. Stretch marks on a growing bump: cocoa, daily, twice a day. A scalp moisturiser for braids that lasts a week: shea, every two or three days.</p>'
      + '<h2>Layering both — yes, it works</h2>'
      + '<p>For very dry winter skin the order is shea first, cocoa on top. Shea penetrates faster, cocoa seals it in. Pick raw, unrefined versions of both — the cheaper refined ones lose the fatty-acid profile that made you want them in the first place.</p>',
    created_at: TS,
  },
];

// CMS-like pages — match the slugs in `src/lib/page-faqs.ts` so the FAQ
// JSON-LD + accordion can preview end-to-end without a database.
export const DEMO_PAGES: Page[] = [
  {
    id: 'demo-page-shipping', slug: 'shipping', title: 'Shipping Policy',
    status: 'published', show_in_footer: true, sort_order: 1,
    meta_title: 'Shipping Policy | Aizel',
    meta_description: 'UK delivery timelines, free-shipping thresholds, and courier partners.',
    excerpt: 'How orders ship across the UK.',
    body_html: '<p>Aizel ships across the United Kingdom via Royal Mail Tracked and DPD. Orders placed before 2 PM ship the same working day.</p><p>Free standard delivery on orders over £30; below that a flat fee is calculated at checkout based on parcel size and destination.</p>',
  },
  {
    id: 'demo-page-returns', slug: 'returns', title: 'Returns & Refunds',
    status: 'published', show_in_footer: true, sort_order: 2,
    meta_title: 'Returns & Refunds | Aizel',
    meta_description: 'Our 14-day return window, who pays for return shipping, and how refunds are issued.',
    excerpt: 'How returns and refunds work.',
    body_html: '<p>You can request a return within 14 days of delivery for unopened items in their original packaging. Damaged or wrong-item shipments are returned at our cost; other reasons are returned at the customer\'s cost.</p><p>Refunds are issued to the original payment method within 5 working days of receiving the returned item, or as store credit if you prefer a faster turnaround.</p>',
  },
  {
    id: 'demo-page-faq', slug: 'faq', title: 'Frequently Asked Questions',
    status: 'published', show_in_footer: true, sort_order: 3,
    meta_title: 'FAQ | Aizel',
    meta_description: 'Common questions about authenticity, order tracking, payment methods, and customer support.',
    excerpt: 'Common questions, answered.',
    body_html: '<p>Browse the most common questions about Aizel. Don\'t see your answer? <a href="/page/contact">Contact us</a> and we\'ll respond within one working day.</p>',
  },
  {
    id: 'demo-page-about', slug: 'about', title: 'About Aizel',
    status: 'published', show_in_footer: true, sort_order: 4,
    meta_title: 'About Us | Aizel',
    meta_description: 'Aizel stocks authentic Afro/Black hair and body care brands and delivers them fast across the UK.',
    excerpt: 'Authentic hair & body care in the UK.',
    body_html: '<p>Aizel brings together the Black hair and body care brands UK shoppers actually want — Cantu, ORS, Palmer\'s, Kuza, ApHogee, KeraCare, Eco Style and more — and delivers them across the United Kingdom. Authentic products, fair prices, fast UK shipping.</p>',
  },
  {
    id: 'demo-page-contact', slug: 'contact', title: 'Contact Us',
    status: 'published', show_in_footer: true, sort_order: 5,
    meta_title: 'Contact | Aizel',
    meta_description: 'Get in touch with Aizel customer support.',
    excerpt: 'Get in touch.',
    body_html: '<p>Reach us at <a href="mailto:hello@aizel.co.uk">hello@aizel.co.uk</a> Monday to Friday. Most enquiries are answered within one working day.</p>',
  },
];

export const DEMO_SITE_SETTINGS: Record<string, string> = {
  store_name: 'Aizel',
  store_email: 'hello@aizel.co.uk',
  currency: 'GBP',
  free_shipping_threshold: '15',
  default_shipping_rate: '4',
  announcement_active: 'true',
  announcement_text: 'Free UK delivery over £30 · Royal Mail Tracked · VAT included',
  announcement_color: '#111827',
  promo_active: 'true',
  promo_label: 'New',
  promo_headline: 'A working preview without a database',
  promo_subline: 'Stub data so you can review layout, a11y, and responsive flow.',
  promo_cta_text: 'Browse the catalogue',
  promo_cta_url: '/shop',
  promo_bg_color: '#6B2C91',
  promo_text_color: '#ffffff',
  hero_headline: 'Hair you love.\n*Brands you trust.*',
  hero_subline: 'Authentic Cantu, ORS, Palmer\'s, Kuza, ApHogee and more — delivered fast across the UK. Free delivery over £30.',
  hero_cta1_text: 'Shop Hair Care',
  hero_cta1_url: '/shop?taxon=hair',
  hero_cta2_text: 'Shop Body Care',
  hero_cta2_url: '/shop?taxon=body',
  hero_brands: 'Cantu,ORS,Palmer\'s,Kuza,ApHogee,KeraCare,Eco Style',
};
